name: "Publish New Version"
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARCHIVE_NAME: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cd build/ && npm i && grunt build-release
      - name: list-stuff
        run: ls -la