name: "Publish New Version"
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARCHIVE_ZIP: concrete-cms-${{ github.event.release.tag_name }}.zip
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cd build/ && npm i && grunt build-release
      - name: Upload Archive
        run: gh release upload ${{ github.event.release.tag_name }} build/${{ env.ARCHIVE_ZIP }}
